runner:
  govet:
    cmd: go vet $(go list ./...)
    format: govet

  gosec:
    cmd: gosec -quiet -no-fail -fmt golint ./...
    format: golint

  staticcheck:
    cmd: staticcheck -fail none $(go list ./...)
    errorformat:
      - "%f:%l:%c: %m"

  golangci:
    cmd: golangci-lint run --out-format=line-number ./...
    errorformat:
      - "%E%f:%l:%c: %m"
      - "%E%f:%l: %m"
      - "%C%.%#"
