name: 🩹 Bug Report
description: Report a bug to help us improve
title: "🩹 Fix: [Brief description of the bug]"
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide the information below to help us understand the issue.

  - type: input
    id: description
    attributes:
      label: "🐛 Bug Description"
      description: "A clear and concise description of what the bug is."
      placeholder: "Describe the bug..."

  - type: textarea
    id: steps
    attributes:
      label: "📋 Steps to Reproduce"
      description: "Steps to reproduce the behavior."
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error

  - type: input
    id: expected
    attributes:
      label: "🖥️ Expected Behavior"
      description: "A clear and concise description of what you expected to happen."
      placeholder: "Describe the expected behavior..."

  - type: textarea
    id: screenshots
    attributes:
      label: "🖥️ Screenshots or Logs"
      description: "If applicable, add screenshots or logs to help explain your problem."
      placeholder: "Attach screenshots or logs..."

  - type: input
    id: environment
    attributes:
      label: "💻 Environment"
      description: "Please provide details about your environment (OS, Go version, browser, etc.)."
      placeholder: "OS: [e.g., Windows 10]\nGo Version: [e.g., 1.23]"

  - type: textarea
    id: additional_context
    attributes:
      label: "📦 Additional Context"
      description: "Add any other context about the problem here, such as recent changes or workarounds."
      placeholder: "Any additional context..."

  - type: textarea
    id: related_issues
    attributes:
      label: "📚 Related Issues"
      description: "If there are any related issues or pull requests, please link them here."
      placeholder: "Link related issues or PRs..."
